# ==========================================================================
# texts/en.py — английские тексты. Набор ключей и {плейсхолдеров} обязан
# совпадать с ru.py (проверяется tests/test_texts.py).
# ==========================================================================

TEXTS_EN = {
    # ---------------- унаследованные тексты (дословно) ----------------
    'greeting': "👋 Hi! Make an online printing order.\n\n📌 We do not edit files — use an online editor or converter if you need to fix a document before printing.\n\n⚠️ Orders with fake names won't be accepted!\n📝 Write your Name and ID (e.g.: Ivanov Ivan Ivanovich, ICG-01-20)",
    'auth_success': "✅ Authorization successful!\n📄 Send the file to print (PDF):",
    'bad_file': "❌ File format not supported! Please send a PDF file.",
    'file_too_big': "❌ File too large! Maximum {max_mb} MB.",
    'file_too_small': "❌ File is too small or corrupted (under {min_kb} KB). Check the file and send again.",
    'pdf_error': "❌ Could not read PDF. Try another.",
    'file_ok': "✅ File accepted! Pages: {total} (🎨{color} / ⚫{bw})\nHow to print?",
    'print_all': "📄 All pages",
    'print_specific': "✂️ Specific pages",
    'choose_pages': "📝 Enter page numbers separated by commas (e.g., 1,3,5-7).\nTotal pages: {total}",
    'color_choice': "🎨 How to print these pages?",
    'color_all': "🎨 All color",
    'bw_all': "⚫ All B&W",
    'color_specific': "📝 Specify color pages",
    'choose_color_pages': "📝 Enter numbers of the pages that should be COLOR (others will be B&W).",
    'format_choice': "📐 What paper size?",
    'sided_choice': "📄 Single-sided or double-sided?",
    'one_side': "1️⃣ Single",
    'two_side': "2️⃣ Double",
    'total_price': "💰 Total for file: {price} RUB.\nAdd another file?",
    'yes': "✅ Yes",
    'no': "❌ No",
    'add_file': "📄 Send the next file:",
    'fold_choice': "📐 Need to fold drawings?",
    'fold_select': "📐 Choose separate drawings to fold (not in a brochure):",
    'fold_done': "✅ Done",
    'fold_none': "❌ No separate drawings to fold. Moving on!",
    'brochure_ask': "📚 Do you need binding?",
    'no_brochure': "📚 No binding needed!",
    'brochure_count': "📚 How many brochures to bind? (Enter number, 0 if none)",
    'choose_brochure': "📚 Assemble Brochure #{num}:\nClick files in the correct order.",
    'brochure_no_files': "❌ You haven't chosen any files for this brochure.",
    'brochure_back': "🔙 Back",
    'brochure_type': "Binding type?",
    'spring': "🔄 Spiral",
    'string': "🧵 String",
    'brochure_saved': "✅ Brochure #{num} done!",
    'brochures_all_done': "✅ All brochures done!",
    'copies_ask_file': "📄 How many copies of file «{name}»? Enter a number:",
    'copies_ask_brochure': "📚 How many copies of Brochure #{num} ({type}) do you need? Enter a number:",
    'copies_set': "✅ Copies set!",
    'enter_number': "❌ Enter 0, 1, 2...",
    'time_choice': "🕐 When will you pick up?\n\n⚡ Express — from 1 minute to 1 hour, +{markup}% on the whole order.",
    'time_express': "⚡ Express",
    'time_1h': "⏱ 1 hour",
    'time_3h': "⏰ 3 hours",
    'time_day': "📅 A day",
    'order_summary_header': "📊 ORDER SUMMARY:",
    'order_summary_file': "📄 File #{num}: {name}\n  📐 {format} | {sided}\n  🎨 Color: {color} | ⚫ B&W: {bw}\n  ×{copies} copies — 💰 {price} RUB.\n",
    'order_summary_brochure': "📚 Brochure #{num} ({type}), files: {file_count} — ×{copies} copies — 💰 {price} RUB.\n",
    'order_summary_express': "⚡ Express surcharge: +{markup}%\n",
    'order_summary_folding': "📐 Folding: {price} RUB.\n",
    'order_summary_total': "\n💰 TOTAL: {total} RUB.\n⏱ Ready by: {ready_time}",
    'sided_single': "Single-sided",
    'sided_double': "Double-sided",
    'final_confirm': "✅ Confirm order",
    'final_cancel': "❌ Cancel",
    'order_confirmed': "✅ ORDER ACCEPTED! Total: {total} RUB.",
    'order_cancelled': "❌ Order cancelled. Press /start",
    'feedback_ask': "📦 Order handed out! Rate the service from 1 to 10:",
    'feedback_bad_rating': "❌ Enter a number from 1 to 10.",
    'feedback_comment': "✅ Thanks! 📝 What can we improve? (or type '-'):",
    'feedback_thanks': "🙏 Thank you for your feedback!",
    'operator_text': "🤖 I can't read free text in this mode. Transfer to an operator?",
    'operator_yes': "👨‍💻 Yes",
    'operator_no': "❌ No",
    'operator_transferred': "✅ Ok, write your question — the operator will see it.",
    'operator_declined': "OK! Send a PDF or press /start to place an order.",
    'operator_sent': "✅ Sent to the operator.",
    'operator_reply_prefix': "👨‍💻 Operator: {text}",
    'working_hours': "⏰ We are closed! Mon-Fri 9:00 to 20:00.",
    'issue_only_hours': "Handing out only 9:00–20:00 (Mon-Fri)!",
    'no_rights': "❌ No rights.",
    'admin_start_blocked': "👑 You are the bot admin. The client dialog is not available to you — client orders arrive in this chat automatically.",
    'generic_error': "❌ Error. Press /start.",
    'not_understood': "🤖 I didn't understand you.",
    'cancel_ask_reason': "✏️ Enter the cancellation reason for client {client_id} (one message):",
    'cancel_notified': "❌ Your order was cancelled.\nReason: {reason}",
    'cancel_done_admin': "✅ Client {client_id} notified about the cancellation.",
    'order_ready_client': "🎉 YOUR ORDER IS READY! Pick it up at the print shop.",

    # ---------------- НОВЫЕ КЛЮЧИ ----------------
    'file_accepted': "✅ File «{name}» accepted! Pages: {total}\nHow to print?",
    'file_one_at_a_time': "📎 I handle files one at a time. Let's finish setting up the current file — you'll be able to send the next one when I ask «Add another file?».\n\n📄 PDF only, from {min_kb} KB to {max_mb} MB.",
    'pages_all': "all",
    'pages_none': "—",

    'auth_invalid': "❌ That doesn't look like a real name and ID.\n📝 Please write it like in the example: Ivanov Ivan Ivanovich, ICG-01-20",

    'brochure_files_exhausted': "ℹ️ No free files left — we'll assemble {done} brochure(s) instead of {planned}.",

    'idle_warning': "⏳ You've been quiet for a while. The dialog will close in {seconds} sec. and the order will have to be started over.\nPress «Continue» if you're still here.",
    'idle_continue': "▶️ Continue",
    'idle_continue_ok': "👍 Let's continue! Please answer the last question.",
    'idle_closed': "🕐 Dialog closed due to inactivity. Press /start to place an order again.",

    'order_again': "\n\n🔁 To place another order, press /start",

    'operator_end_button': "🔚 End the chat",
    'operator_closed': "✅ The chat with the operator is closed.\n🔁 Press /start to place an order.",

    'admin_operator_request': "👤 Client {client_id} is asking for an operator.",
    'admin_operator_message': "📩 Message from {client_id}:\n{text}",
    'admin_reply_button': "✍️ Reply to client",
    'admin_reply_ask': "✏️ Write your reply to client {client_id} in one message:",
    'admin_reply_sent': "✅ Reply sent to client {client_id}.",

    'summary_pages_print': "  📄 Print pages: {pages}\n",
    'summary_pages_color': "  🎨 Color pages: {pages}\n",
    'summary_pages_bw': "  ⚫ B&W pages: {pages}\n",
}
